language: node_js
node_js:
  - "10"
sudo: required
addons:
  firefox: latest
  apt-get:
    sources:
      - google-chrome
    command:
      -$ wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    packages:
      - google-chrome-stable fluxbox
before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FA_AUTH_TOKEN}" >> ~/.npmrc
services:
  - xvfb
script:
  - npm run build
before_deploy:
  - rm -rf node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "atlas.phila.gov"
    on:
      branch: master
    local_dir: dist
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "atlas-dev.phila.gov"
    on:
      branch: develop
    local_dir: dist
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "atlas-dev2.phila.gov"
    on:
      branch: vue-router
    local_dir: dist
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "atlas-dev3.phila.gov"
    on:
      branch: no-leaflet
    local_dir: dist
    skip_cleanup: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "atlas-cleanup"
    on:
      branch: cleanup
    local_dir: dist
    skip_cleanup: true
