version: '3'

services:
  testcafe:
    container_name: testcafe_${BROWSER}
    image: testcafe/testcafe
    environment:
      - NODE_PATH=./node_modules/testcafe/node_modules:/opt
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    volumes:
    - ./node_modules/dotenv:/node_modules/dotenv
    - ./.env:/.env
    - ./Testcafe:/tests
    - ./screenshots:/screenshots
    - ./reports:/reports
    entrypoint: ["/opt/testcafe/docker/testcafe-docker.sh", "${BROWSER}", "/tests/Tests/*.ts", "-S", "-s", "screenshots", "-r", "json:reports/report.json", "-e","--dev"]