# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: dev Push to S3

on:
  push:
    branches:
      - lead-cert

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
  
      - name: install npm 6
        run: |
          npm install -g npm@6
      
      - name: npm install, and build
        run: |
          printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}" >> ~/.npmrc
          git config --global url."https://".insteadOf ssh://
          npm ci
          npm run build
      env:
        FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FA_AUTH_TOKEN }}
        VUE_APP_GATEKEEPER_KEY: ${{ secrets.VUE_APP_GATEKEEPER_KEY }}
        VUE_APP_CYCLOMEDIA_API_KEY: ${{ secrets.VUE_APP_CYCLOMEDIA_API_KEY }}
        VUE_APP_CYCLOMEDIA_PASSWORD: ${{ secrets.VUE_APP_CYCLOMEDIA_PASSWORD }}
        VUE_APP_CYCLOMEDIA_USERNAME: ${{ secrets.VUE_APP_CYCLOMEDIA_USERNAME }}
        VUE_APP_PICTOMETRY_API_KEY: ${{ secrets.VUE_APP_PICTOMETRY_API_KEY }}
        VUE_APP_PICTOMETRY_SECRET_KEY: ${{ secrets.VUE_APP_PICTOMETRY_SECRET_KEY }}

    - name: Deploy to Dev s3, Set index headers, and Invalidate Cloudfront
      env:
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_S3_BUCKET: atlas-dev2.phila.gov
        AWS_CLOUDFRONT_DISTRIBUTION: E3DWSPDEMV5HQI
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 sync dist s3://$AWS_S3_BUCKET --region us-east-1 --delete
        aws s3 cp s3://$AWS_S3_BUCKET s3://$AWS_S3_BUCKET --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --acl public-read --cache-control max-age=0,no-cache,no-store,must-revalidate,proxy-revalidate,public --expires "0" --content-type "text/html; charset=utf-8"
        aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION --paths "/*"
